name: GoldenChestEconomy
main: me.igwb.GoldenChest.GoldenChestEconomy
version: 1.0
soft-depend: [LWC, Vault]
commands:
   money:
      description: Check how much money someone has.
      usage: /money [player]
      permission: GoldenChestEconomy.use.money
      permission-message: You don't have permission to use that command!
   balance:
      description: Check how much money someone has.
      usage: /money [player]
      permission: GoldenChestEconomy.use.money
      permission-message: You don't have permission to use that command!
   bal:
      description: Check how much money someone has.
      usage: /money [player]
      permission: GoldenChestEconomy.use.money
      permission-message: You don't have permission to use that command!
   pay:
      description: Pays money to a player.
      usage: /pay [player] [amount]
      permission: GoldenChestEconomy.use.pay
      permission-message: You don't have permission to use that command!
   registerChest:
      description: Registers a chest.
      usage: /registerChest
      permission: GoldenChestEconomy.use.registerChest
      permission-message: You don't have permission to use that command!
   top:
      description: Lists all accounts in a list ordered by their balance.
      usage: /top [page]
      permission: GoldenChestEconomy.use.top
      permission-message: You don't have permission to use that command!
   grant:
      description: Gives a player the specified amount of money.
      usage: /grant [player] [amount]
      permission: GoldenChestEconomy.admin.grant
      permission-message: You don't have permission to use that command!
   take:
      description: Takes a specified amount of money from a player.
      usage: /take [player] [amount]
      permission: GoldenChestEconomy.admin.take
      permission-message: You don't have permission to use that command!