name: GoldenChestEconomy
main: me.igwb.GoldenChest.GoldenChestEconomy
version: 1.0
soft-depend: [LWC]
commands:
   money:
      description: Check how much money someone has.
      usage: /money [player]
      permission: GoldenChest.money
      permission-message: You don't have permission to use that command!
   balance:
      description: Check how much money someone has.
      usage: /money [player]
      permission: GoldenChest.money
      permission-message: You don't have permission to use that command!
   bal:
      description: Check how much money someone has.
      usage: /money [player]
      permission: GoldenChest.money
      permission-message: You don't have permission to use that command!
   grant:
      description: Gives a player the specified of money.
      usage: /grant [player] [amount]
      permission: GoldenChest.grant
      permission-message: You don't have permission to use that command!
   take:
      description: Takes a specified amount of money from a player.
      usage: /take [player] [amount]
      permission: GoldenChest.take
      permission-message: You don't have permission to use that command!
   pay:
      description: Pays money to a player.
      usage: /pay [player] [amount]
      permission: GoldenChest.pay
      permission-message: You don't have permission to use that command!
   registerChest:
      description: Registers a chest.
      usage: /registerChest
      permission: GoldenChest.registerChest
      permission-message: You don't have permission to use that command!